version: "3.8"

services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    image: rabbitmq-local:latest
    container_name: rabbitmqids
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mei-ids-network

  moodleapp:
    build:
      context: ./moodle
      dockerfile: Dockerfile
    image: moodleapp:1.0
    container_name: moodleapp
    ports:
      - "80:80"
    volumes:
      - moodledata:/var/www/moodledata
      # - moodleconfig:/var/www/html/config.php:rw
    depends_on:
      - moodledb
    networks:
      - mei-ids-network

  moodledb:
    image: mysql:8.4.5
    container_name: clouddb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    volumes:
      - clouddbdata:/var/lib/mysql
    networks:
      - mei-ids-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: clouddb
      PMA_PORT: 3306
      PMA_USER: moodleuser
      PMA_PASSWORD: moodlepass
    depends_on:
      - moodledb
    networks:
      - mei-ids-network

volumes:
  rabbitmq_data:
    name: mei_ids_rabbitmq_data
  clouddbdata:
  moodledata:
  moodleconfig:

networks:
  mei-ids-network:
    name: mei-ids-network
